// Ce fichier est généré automatiquement, ne pas modifier à la main.
export const JOBS_MAPPING: Record<string, string> = {
    "gendarme": "Gendarme",
    "eri": "ERI",
    "psig": "PSIG",
    "officiergendarme": "Officier Gendarme",
    "pdgn": "PDGN",
    "generalgm": "Général Gendarme",
    "gign": "GIGN",
    "citoyen": "Citoyen",
    "cuisinier": "Cuisinier",
    "banquier": "Banquier",
    "armurier": "Armurier",
    "medecin": "Medecin",
    "ambulancier": "SAMU",
    "mafieux": "Mafieux",
    "parrain": "Parrain de la mafia",
    "Gangster": "Gangster",
    "CGangster": "Chef des gangsters",
    "Yakuza": "Yakuza",
    "CYakuza": "Chef Yakuza",
    "crips": "Crips",
    "ccrips": "Chef Crips",
    "cbloods": "Chef Bloods",
    "bloods": "Bloods",
    "armurier_illegal": "Marchand d'armes",
    "voleur": "Voleur",
    "staff": "Staff",
};
