// Auto-generated jobs mapping
export const jobsMapping = {
  4: "Gendarme",
  5: "ERI",
  6: "PSIG",
  7: "Officier Gendarme",
  8: "PDGN",
  9: "Général Gendarme",
  10: "GIGN",
  11: "Citoyen",
  12: "Cuisinier",
  13: "Banquier",
  14: "Armurier",
  15: "Medecin",
  16: "SAMU",
  17: "Mafieux",
  18: "Parrain de la mafia",
  19: "Gangster",
  20: "Chef des gangsters",
  21: "Yakuza",
  22: "Chef Yakuza",
  23: "Crips",
  24: "Chef Crips",
  25: "Chef Bloods",
  26: "Bloods",
  27: "Marchand d'armes",
  28: "Voleur",
  29: "Staff"
} as const;
